### PR TITLE
add detail about creating effective objectives

### PR DESCRIPTION
**Pull request by ultrasaurus**
Added section on Objectives, Measures, and pulled example from recent Engineering OKRs which have more measurable outcomes than previous examples.  Also added "review" section for readability.

### CODE REVIEW

**Comment by mbland** [comment]
This looks good, but I'm interested in seeing where @brethauer's recommendation leads.

**Comment by ultrasaurus** [comment]
@mbland -- I'm 100% in favor of  @brethauer suggestion.  It's aligned with some of the ideas from my original pull request.  Happy to update the pull request if you agree with integrating these suggestions:

from @brethauer in other venue: 
move toward "Outcomes" as the "O" in OKRs, rather than objectives.  

There are many benefits to this.  
#1, Outcomes are really the best form of objectives.  An outcome (impact) is always what you are trying to achieve in the end.
#2 "Objectives" in the current OKR model cause confusion, because they can be either outcomes or actions.  Shifting primary focus to outcomes would provide more consistency in the model.
#3  Outcomes and metrics are the outputs of the first part of the lean ux process, so the process for creating OKRs would become cleaner.  

As I envision it, this wouldn't impact the model much at all, other than making it more clear.
The format would end up looking something like this:

Outcome 1
- Metric A that we can use to measure progress against this outcome
- Metric B that we can use to measure progress against this outcome

Actions for Outcome 1:
- Action A we believe  will result in outcome 1
- Action B we believe will result in outcome 1

The team can then measure it's progress (using the 0.1 scale) against the action(s), and (more importantly) progress against the outcome, using the metrics it defined.

**Comment by mbland** [comment]
I'd say give it a shot, @ultrasaurus.

**Comment by ultrasaurus** [comment]
So, the Lean UX framework uses "Outcomes and Metrics," but I might lean toward  "Outcomes and Measures" since I think people tend to think of metrics as quantifiable metrics, but measures feels more inclusive to qualitiative evaluation.  

Any thoughts on naming?

**Comment by khandelwal** [comment]
I feel like a metric is how things are judged, whereas a measure is just a way to measure something. Getting people to get comfortable with qualitative metrics should be relatively easy with examples, etc.

**Comment by brethauer** [comment]
@ultrasaurus I very much like the consideration toward naming, and I agree that metrics probably sounds scary or implies quantitative for some people - but it might be a bit better choice.

A quick snippet from https://cio.gov/performance-metrics-and-measures/ 

_Measures vs. Metrics
There is overlap between measures and metrics. Both can be qualitative or quantitative, but what distinguishes them is important. Measures are concrete, usually measure one thing, and are quantitative in nature (e.g. I have five apples). Metrics describe a quality and require a measurement baseline (I have five more apples than I did yesterday). In a Section 508 program, measures are useful for demonstrating workloads and activity, and metrics are useful for evaluating compliance, processes effectiveness, and measuring success against established objectives._

What I'm getting out of that is that a metric has context, where a measure is more a "piece of data" that informs a metric.  My vote would be go with "metric" but be careful to make sure people understand it can be both qual/quant.

**Comment by ultrasaurus** [comment]
Interesting reference.  I'm so excited that our USGov CIOs are talking about outcomes, metrics and measures, that I'm convinced we should use their lingo!  working on next draft... stay tuned.

**Comment by ultrasaurus** [comment]
sorry, to lose split the discussion, but I did a rebase and can't easily put my changes on top of here.  Please see:  https://github.com/18F/grouplet-playbook/pull/5

**Pull request closed without merging**
