### PR TITLE
Remove references to external resources, licenses.

### PR DESCRIPTION
**Pull request by andrewmaier**

### CODE REVIEW

**Comment by mbland** [comment]
Why?

**Comment by andrewmaier** [comment]
Skimming the presentation isn't helping me comprehend this :)

**Comment by mbland** [comment]
That's beside the point. The external reference is a required license notice.

**Comment by andrewmaier** [comment]
@mbland I don't agree, but there are some other changes in this branch that are worth keeping. I'll get your external links back in.

**Comment by gbinal** [comment]
+1 to the external links.   I don't understand why you'd remove them.    

A heads up that it's hard to see what other edits you're trying to make b/c of how much you changed the link breaks, @Andrewmaier.

**Comment by andrewmaier** [comment]
@gbinal Do you mean line breaks?

**Comment by gbinal** [comment]
Sorry, yes.

**Pull request closed without merging**
